JoinLeave:
  welcome-again: "Welcome back to our server $player"
  welcome: "Welcome $player we hope you enjoy your stay here"
  leave: "$player has left the galaxy. Let's hope they have a safe travel!!!"
Classes:
  DpsBuffMulti: 1
  HealerBuffMulti: 1
  TankBuffMulti: 10