JoinLeave:
  welcome-again: "Welcome back to our server $player"
  welcome: "Welcome $player we hope you enjoy your stay here"
  leave: "$player has left the galaxy. Let's hope they have a safe travel!!!"
Classes:
  DpsBuffMultiplier: 1
  HealerBuffMultiplier: 1
  TankBuffMultiplier: 9
  Minerbuffmultiplier: 1
  Diverbuffmultiplier: 1
  allowedwords:
    - "Wilderness"
    - "Wilderness_nether"
    - "Wilderness_the_end"
  CommandCooldown: 10