name: EGCustom
version: '${project.version}'
main: me.hephaestus2023.test.EGCustom
api-version: 1.18
commands:
  Class:
    description: this command allows for a class to be selected
    usage: /<command>
  reload-Test:
    description: This reloads the server
    usage: /<command>
    permission: Test.Reload