name: EGCustom
version: '${project.version}'
main: me.hephaestus2023.test.EGCustom
api-version: 1.18
commands:
  Checker:
    description: Checks the class of a player
    usage: /<command>
    permission: EGCustom.ClassChecker
  Class:
    description: this command allows for a class to be selected
    usage: /<command>